### ISSUE TITLE
Is it possible to specify to change browser from Firefox to Firefox Nightly

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-firefox#2]
I setup the workflow and it runs well. Only issue that on activation it does nothing as I don't have Firefox installed but instead use [Firefox Nightly](https://www.mozilla.org/en-GB/firefox/channel/desktop/). 

I couldn't find in settings if it's possible to change the app. I think it would be a nice feature as not everyone uses default Firefox.

Thank you.

**Comment by deanishe** [comment]
Did you install the extension in Firefox Nightly?

**Comment by nikitavoloboev** [comment]
I have

**Comment by deanishe** [comment]
Then it should work. Check the logs.

**Comment by nikitavoloboev** [comment]
```
\------------------------/
[21:38:11.903] Firefox Assistant[Debug] Processing complete
[21:38:11.904] Firefox Assistant[Debug] Passing output 'about:blank' to Conditional
[21:38:11.905] Firefox Assistant[Conditional] Processing complete
[21:38:11.906] Firefox Assistant[Conditional] Passing output 'about:blank' to Hide Alfred
[21:38:11.984] Firefox Assistant[Hide Alfred] Processing complete
[21:38:11.986] Firefox Assistant[Hide Alfred] Passing output 'about:blank' to Debug
[21:38:11.986] Firefox Assistant[Debug] .
/------------------------\
query=about:blank
variables={
  ACTION = "Activate Tab"
  AW_SESSION_ID = "E79WT0R2BXBJY0X4DM4DIFNZ"
  CMD = "tab"
  TAB = "1"
  TAB_CTRL = ""
  TAB_GODOC = ""
  TITLE = "New Tab"
  URL = "about:blank"
  URL_DEFAULT = "Open in Default Application"
  URL_OPT = "Open in Safari"
}
\------------------------/
[21:38:11.988] Firefox Assistant[Debug] Processing complete
[21:38:11.989] Firefox Assistant[Debug] Passing output 'about:blank' to Run Script
[21:38:12.169] ERROR: Firefox Assistant[Run Script] 21:38:11 workflow_paths.go:143: [warning] info.plist not found. Guessed: /Users/nikivi/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6924C26A-9B69-42A0-ACBE-73D94B15B7F6
🍺
21:38:11 workflow.go:327: ----- Firefox Assistant/0.1.0 (AwGo/0.20.2) ------
21:38:11 actions.go:83: loaded URL action "Open in Firefox" from "~/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6924C26A-9B69-42A0-ACBE-73D94B15B7F6/scripts/Open in Firefox.sh"
21:38:11 actions.go:83: loaded URL action "Open in Safari" from "~/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6924C26A-9B69-42A0-ACBE-73D94B15B7F6/scripts/Open in Safari.sh"
21:38:11 actions.go:83: loaded URL action "Open in Chrome" from "~/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6924C26A-9B69-42A0-ACBE-73D94B15B7F6/scripts/Open in Chrome.sh"
21:38:11 actions.go:83: loaded URL action "Open in Default Application" from "~/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6924C26A-9B69-42A0-ACBE-73D94B15B7F6/scripts/Open in Default Application.sh"
21:38:11 client.go:348: running action "Activate Tab" on tab #1 ...
21:38:12 scripts.go:167: ------------- [/usr/bin/osascript -l AppleScript -e tell application "Firefox" to activate] ---------------
21:38:12 scripts.go:168: 30:38: execution error: Can’t get application "Firefox". (-1728)

21:38:12 scripts.go:169: ----------------------------------------------
21:38:12 workflow.go:342: ------------------ FATAL ERROR -------------------
21:38:12 workflow.go:343: exit status 1 : goroutine 1 [running]:
runtime/debug.Stack(0xc000123d00, 0x1, 0x1)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/deanishe/awgo.(*Workflow).Run.func2(0xc0000f10e0)
	/Users/daj/pkg/mod/github.com/deanishe/awgo@v0.22.0/workflow.go:343 +0xe7
panic(0x14910a0, 0xc0000cb2a0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:679 +0x1b2
main.run()
	/Users/daj/Code/Alfred/alfred-firefox-assistant/main.go:141 +0x1c8
github.com/deanishe/awgo.(*Workflow).Run(0xc0000f10e0, 0x14d0458)
	/Users/daj/pkg/mod/github.com/deanishe/awgo@v0.22.0/workflow.go:357 +0x2af
main.main()
	/Users/daj/Code/Alfred/alfred-firefox-assistant/main.go:145 +0x39
21:38:12 workflow.go:344: ---------------- END STACK TRACE -----------------
21:38:12 workflow.go:375: [ERROR] exit status 1
21:38:12 workflow.go:378: Get help at https://github.com/deanishe/alfred-firefox/issues
21:38:12 workflow.go:401: ------------------ 166.150745ms ------------------
```

These lines

```
21:38:12 scripts.go:167: ------------- [/usr/bin/osascript -l AppleScript -e tell application "Firefox" to activate] ---------------
21:38:12 scripts.go:168: 30:38: execution error: Can’t get application "Firefox". (-1728)
```

Say I don't have Firefox which I don't. I was thinking it would be nice to allow changing the application that gets called to a custom one like Firefox Nightly.

**Comment by deanishe** [comment]
So what you actually mean is "the activate tab function doesn't work on Firefox Nightly"?

**Comment by nikitavoloboev** [comment]
Yes. Sorry, could of been more clearer initially.

**Comment by deanishe** [comment]
I'll think about making it possible to specify beta or developer edition. There are a few places where the workflow does explicitly call Firefox and not just the extension.

But generally, I'm not a fan of supporting beta software, and the workflow/extension will not work with multiple Firefoxes running at the same time.
