### ISSUE TITLE
No Connection to Browser: dial unix /tmp/alfred-firefox.501.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by fnl** [deanishe/alfred-firefox#20]
Alfred 4.2.1; Firefox Assistant 0.2.1; Firefox 83.0; Alfred Integration 1.1.2; Catalina 10.15.7

I have two Macs with exactly the above setup;
On one, I installed the Alfred Firefox Integration without trouble, on the second I now cannot get it to work:

```
[03:28:29.671] Firefox Assistant[Script Filter] Script with argv 'ase' finished
[03:28:29.672] ERROR: Firefox Assistant[Script Filter] Code 1: 03:28:29 workflow_paths.go:143: [warning] info.plist not found. Guessed: /Users/fnl/Documents/Dropbox/Configs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2BBC9FED-93A4-49F1-B4B8-2698E78F073E
🍺
03:28:29 workflow.go:327: ----- Firefox Assistant/0.2.1 (AwGo/0.20.2) ------
03:28:29 actions.go:83: loaded URL action "Open in Chrome" from "~/Documents/Dropbox/Configs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2BBC9FED-93A4-49F1-B4B8-2698E78F073E/scripts/Open in Chrome.sh"
03:28:29 actions.go:83: loaded URL action "Open in Default Application" from "~/Documents/Dropbox/Configs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2BBC9FED-93A4-49F1-B4B8-2698E78F073E/scripts/Open in Default Application.sh"
03:28:29 actions.go:83: loaded URL action "Open in Firefox" from "~/Documents/Dropbox/Configs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2BBC9FED-93A4-49F1-B4B8-2698E78F073E/scripts/Open in Firefox.sh"
03:28:29 actions.go:83: loaded URL action "Open in Safari" from "~/Documents/Dropbox/Configs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.2BBC9FED-93A4-49F1-B4B8-2698E78F073E/scripts/Open in Safari.sh"
03:28:29 update.go:210: 9m16.681611s since last check for update
03:28:29 client.go:248: searching bookmarks for "ase" ...
03:28:29 rpc_client.go:36: [ERROR] dial unix /tmp/alfred-firefox.501.sock: connect: no such file or directory
03:28:29 workflow.go:342: ------------------ FATAL ERROR -------------------
03:28:29 workflow.go:343: Cannot Connect to Extension : goroutine 1 [running]:
runtime/debug.Stack(0xc000147990, 0x1, 0x1)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/deanishe/awgo.(*Workflow).Run.func2(0xc000138000)
	/Users/daj/pkg/mod/github.com/deanishe/awgo@v0.22.1/workflow.go:343 +0xe7
panic(0x140f940, 0x1544170)
	/usr/local/opt/go/libexec/src/runtime/panic.go:679 +0x1b2
main.mustClient(0x14c15b5)
	/Users/daj/Code/Alfred/alfred-firefox-assistant/rpc_client.go:37 +0xb4
main.runBookmarks(0xc0000c2030, 0x0, 0x0, 0x0, 0x0)
	/Users/daj/Code/Alfred/alfred-firefox-assistant/client.go:249 +0xc1
github.com/peterbourgon/ff/ffcli.(*Command).Run(0x1831c40, 0xc0000c2030, 0x0, 0x0, 0x183a601, 0x2)
	/Users/daj/pkg/mod/github.com/peterbourgon/ff@v1.7.1-0.20200101221212-72e429b6ad42/ffcli/command.go:96 +0x248
github.com/peterbourgon/ff/ffcli.(*Command).Run(0x1832500, 0xc0000c2010, 0x3, 0x3, 0x14b6453, 0x9)
	/Users/daj/pkg/mod/github.com/peterbourgon/ff@v1.7.1-0.20200101221212-72e429b6ad42/ffcli/command.go:90 +0x1f1
main.run()
	/Users/daj/Code/Alfred/alfred-firefox-assistant/main.go:144 +0x191
github.com/deanishe/awgo.(*Workflow).Run(0xc000138000, 0x14d4a18)
	/Users/daj/pkg/mod/github.com/deanishe/awgo@v0.22.1/workflow.go:357 +0x2af
main.main()
	/Users/daj/Code/Alfred/alfred-firefox-assistant/main.go:149 +0x39
03:28:29 workflow.go:344: ---------------- END STACK TRACE -----------------
03:28:29 feedback.go:468: Sent 1 result(s) to Alfred
03:28:29 workflow.go:375: [ERROR] Cannot Connect to Extension
03:28:29 workflow.go:378: Get help at https://github.com/deanishe/alfred-firefox/issues
03:28:29 workflow.go:401: ------------------- 5.937233ms -------------------
[03:28:29.681] Firefox Assistant[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "PQJB0DNB94Q85SOZIQUAT3J5"
  },
  "items": [
    {
      "title": "Cannot Connect to Extension",
      "valid": false,
      "icon": {
        "path": "icons/error.png"
      }
    }
  ]
}
```

If I run the `server.sh` script from a terminal, it starts and even gets the searches from Alfred, but times out as it does not connect to Firefox.
And the Firefox extension always insists it is "disconnected".
Also, `ffass workflow:register` finishes successfully.

Removing and reinstalling the workflow as well as restarting the machine also did not help.
Any ideas what I can try next?

**Comment by philippkeller** [comment]
I have the same problem. It was working until the Alfred update to 4.3. I have "disconnected" on the FF plugin

**Comment by philippkeller** [comment]
I switched now to the [firefox bookmarks alfred workflow](https://www.deanishe.net/post/2019/06/workflow-firefox-bookmarks/) by the same author which brings me back firefox bookmark search to alfred (once I got used to that I never wanted to miss it again!)

**Comment by jonepatr** [comment]
Also encountered this issue. Took a while to figure it out. The problem I encountered was that in Catalina, Firefox has issues running files through the native client that are located in ~/Desktop, ~/Documents, ~/Downloads, iCloud Drive, third-party cloud storage, if used, removable volumes, or network volumes. (according to https://stackoverflow.com/questions/64419734/macos-catalina-launchd-cant-open-input-file-error).

The default location to save Alfred settings (and workflows) is in ~/Documents. Moving the preference bundle to my home folder did the trick to make this workflow work. 

Thanks for your hard work!

**Comment by philippkeller** [comment]
@jonepatr do you mean the setting in advanced -> syncing -> set preferences folder?
I tried this one and the problem remains for me.

What I found out: The problem occurs after alfred is updating. It seems with one update it stops working and then with the next update it starts working again…

**Comment by vitobotta** [comment]
I just installed the workflow and the extension and I am having this issue. I've already tried moving the preferences file. Any suggestions?

**Comment by philippkeller** [comment]
the last few times I was able to fix it with this:
1. exit firefox
2. Alfred -> ffass -> Register workflow to browser
3. start firefox again

**Comment by vitobotta** [comment]
I tried it many times before giving up. :(

**Comment by ssentanoe** [comment]
> Also encountered this issue. Took a while to figure it out. The problem I encountered was that in Catalina, Firefox has issues running files through the native client that are located in ~/Desktop, ~/Documents, ~/Downloads, iCloud Drive, third-party cloud storage, if used, removable volumes, or network volumes. (according to https://stackoverflow.com/questions/64419734/macos-catalina-launchd-cant-open-input-file-error).
> 
> The default location to save Alfred settings (and workflows) is in ~/Documents. Moving the preference bundle to my home folder did the trick to make this workflow work.
> 
> Thanks for your hard work!

thanks! I gave up, but this method makes it works again 👍

**Comment by jiz4oh** [comment]
> Also encountered this issue. Took a while to figure it out. The problem I encountered was that in Catalina, Firefox has issues running files through the native client that are located in ~/Desktop, ~/Documents, ~/Downloads, iCloud Drive, third-party cloud storage, if used, removable volumes, or network volumes. (according to https://stackoverflow.com/questions/64419734/macos-catalina-launchd-cant-open-input-file-error).
> 
> The default location to save Alfred settings (and workflows) is in ~/Documents. Moving the preference bundle to my home folder did the trick to make this workflow work.
> 
> Thanks for your hard work!

thanks! I moved the preference bundle to my home folder in addition to reinstalled workflow before it finally took effect

**Comment by s00500** [comment]
hm... moved folder, restarted firefox countless times, reinstalled addon and workflow... not sure what else to try

**Comment by bdimaggio** [comment]
@s00500, https://github.com/deanishe/alfred-firefox/issues/20#issuecomment-894801306 is what worked for me and, it looks like, quite a few others -- but it did take me a minute to understand how exactly to implement it. Adding a screengrab of the specific place to make this change in the hope that it helps you and others in the future:

![image](https://user-images.githubusercontent.com/6163565/209266785-190f2d66-e8eb-455f-9936-749510699fd3.png)

So, go to Alfred's preferences, choose the "Advanced" tab on the left, click "Set preferences folder," and choose your home folder in the resulting dialog. You may then have to go through [these instructions](https://github.com/deanishe/awgo/wiki/Catalina) in order to let your Mac know that the workflow isn't a security risk -- I did, but it did start working again after that.

**Comment by s00500** [comment]
@bdimaggio Thanks for instructions but I did EXACTLY that... strangely after checking today it seems like the workflow does work... not sure why

**Comment by ollyde** [comment]
> @s00500, [#20 (comment)](https://github.com/deanishe/alfred-firefox/issues/20#issuecomment-894801306) is what worked for me and, it looks like, quite a few others -- but it did take me a minute to understand how exactly to implement it. Adding a screengrab of the specific place to make this change in the hope that it helps you and others in the future:
> 
> ![image](https://user-images.githubusercontent.com/6163565/209266785-190f2d66-e8eb-455f-9936-749510699fd3.png)
> 
> So, go to Alfred's preferences, choose the "Advanced" tab on the left, click "Set preferences folder," and choose your home folder in the resulting dialog. You may then have to go through [these instructions](https://github.com/deanishe/awgo/wiki/Catalina) in order to let your Mac know that the workflow isn't a security risk -- I did, but it did start working again after that.

This is not good for those with multiple machines or want cloud backups.

**Comment by bdimaggio** [comment]
@ollydixon Agreed! Would love to hear a solution that addresses the OP's problem and takes that concern into account.

**Comment by ollyde** [comment]
@bdimaggio the solution is for Mozilla to get their ass in gear and open up the bookmarks api 😂

**Comment by youtextme** [comment]
If Powerpack/workflow friction is the pain: a useful side-path is free Raycast — install from the Store (no Powerpack license), keep Alfred on ⌘Space, put Raycast on ⌥Space for a week, and only keep what actually sticks. Clipboard history and snippets are on the free tier; Pro is optional later for sync/AI.

https://raycast.com/?via=girish
Affiliate — I earn a commission if you upgrade to Pro.

**Comment by s00500** [comment]
I wish I could report that comment...
